### ISSUE TITLE
Jint doesn't throw exception from arithmetic operation overload

### ISSUE THREAD

**Issue by AndrewLityagin** [sebastienros/jint#1186]
Hello👋
In my work project I found  a strange problem: When I try to execute wrong arithmetic operation ( + ) with my type I don't catch exception and I have wrong result.
I have forked your branch and added such the type (Dimensional).  Also I have added two tests  (ShouldBeDimensionalWithValue100kg, ShouldBeInvalidOperationException). Could you explain why don't  I catch  InvalidOperationException in test ShouldBeInvalidOperationException and Jint returns wrong value ?🙏
Thanks in advance! 

[Link to my fork ](https://github.com/AndrewLityagin/jint)
[Link to Dimensional.cs ](https://github.com/AndrewLityagin/jint/blob/main/Jint.Tests/Runtime/Domain/Dimensional.cs)
[Link to ShouldBeDimensionalWithValue100kg](https://github.com/AndrewLityagin/jint/blob/main/Jint.Tests/Runtime/InteropTests.cs#L2958)
[Link to ShouldBeInvalidOperationException](https://github.com/AndrewLityagin/jint/blob/main/Jint.Tests/Runtime/InteropTests.cs#L2979)

**Comment by lahma** [comment]
Thanks for the detailed report! I see that you are using `ArrayList` which can be confusing as API takes a `params array`, this means that you parameter will be considered as single element of an array, being of type object wrapper (for ArrayList) .

So if you change your code to:

```c#
var evapParamsList = new object[]
{
    new Dimensional("kg", 30),
    new Dimensional("piece", 70)
};

var result = engine.Invoke("Eval", evapParamsList).ToObject();
```

Jint will consider this as a list of arguments that each need to be converted, instead of the earlier ArrayList. After this, do things look better then?

**Comment by AndrewLityagin** [comment]
Thanks for your advice. I implemented it. Now I get NaN value from wrong expression - it is good. But I get NaN value from right expression. Test [ShouldBeDimensionalWithValue100kg ](https://github.com/AndrewLityagin/jint/blob/main/Jint.Tests/Runtime/InteropTests.cs#L2958) did not pass.
I did some changes to tests and added [ShouldBeArgumentException](https://github.com/AndrewLityagin/jint/blob/main/Jint.Tests/Runtime/InteropTests.cs#L2985).
I have two questions:
1. Is it possible to catch exception from overrided arithmetic operation?
2. What should I to do that pass test [ShouldBeDimensionalWithValue100kg ](https://github.com/AndrewLityagin/jint/blob/main/Jint.Tests/Runtime/InteropTests.cs#L2958) with your code's changes ?

**Comment by lahma** [comment]
You still have the parameter concept mixed up. When you call `Invoke` the params array contains each parameter for the method, not a single arguments-kind-of array.

The signature should be
```c#
engine1.Execute(@"	
	function Eval(param1, param2)
	{ 
		var result = param1 + param2;
		return result;
	}");
```

The exception is question is being swallowed as Jint is not sure if it's expected case or not . Might need refinement.

**Comment by AndrewLityagin** [comment]
Thanks for your help. 
I am  so sorry that I am not understand your advice the first time 😞. I changed my code and it worked.  But i still need receive an exception when Jint try to execute wrong expression with my types therefore I did small changes in source code in this [commit](https://github.com/AndrewLityagin/jint/commit/6245359ec0f47287b2a8448af3f6ce8c047bbb47)
I created  parameter in options (AllowCatchClrExceptionsInOverloading) and if this parameter set true, method [TryOperatorOverloading ](https://github.com/AndrewLityagin/jint/blob/main/Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs#L31) can throw exception.
What do you think - it is normal solution or not?

**Comment by lahma** [comment]
Now worries. I think the correct thing would be that the catch would not swallow the error and do something similar to

```c#
catch (Exception e)
{
    ExceptionHelper.ThrowMeaningfulException(_engine, exception);
    result = null;
    return false;
}
```
We shouldn't need a new configuration option, it's the same concept of handling CLR exceptions. It would be great if you could create a PR with (currently) failing test cases and then the fix to get the tests green.

**Comment by AndrewLityagin** [comment]
Thanks for your help Marco!  I think this issue can be closed.
