### ISSUE TITLE
Catch block doesn't catch error thrown by `JSON.parse('01')`

### ISSUE THREAD

**Issue by atifaziz** [sebastienros/jint#614]
Jint REPL demo of bug:

```
Welcome to Jint (1.0.0.0)
Type 'exit' to leave, 'print()' to write on the console.

jint> JSON.parse('1') // ok
=> 1
jint> JSON.parse('[01]') // not ok and throws as expected
Unexpected token {0}
jint> try { JSON.parse('01') } catch (e) {} // exception is not caught by the catch block?!?
Unexpected token {0}
```

**Comment by lahma** [comment]
The logic was throwing ArgumentException and only JavaScriptExceptions are candidate for graceful JS handling, should be fixed now. Thanks for reporting.

**Comment by Ivan-VisesTech** [comment]
Still not fixed, try:

try { JSON.parse(' ') } catch (e) {}

or:

try { JSON.parse('') } catch (e) {}
